name: Render Cookiecutter Template

on:
  workflow_dispatch: # Manual trigger

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Sets up Python on the runner
      with:
        python-version: '3.x' # Specify your desired Python version

    - name: Install Cookiecutter
      run: pip install cookiecutter # Installs the Cookiecutter package

    - name: Render template
      run: cookiecutter ./.skeleton --no-input -o ./rendered # Renders the template using Cookiecutter and outputs to the 'rendered' directory

    - name: Configure Git
      run: |
        git config user.name "Tony Bushinger"
        git config user.email "tbushinger@gmail.com" # Configure Git identity for the bot

    - name: Commit and push changes
      run: |
        cd rendered # Navigate to the rendered output directory
        git add . # Add all changes
        git commit -m "Render Cookiecutter template" || echo "No changes to commit" # Commit changes, continue if no changes
        git push # Push changes to the repository

